@url = http://localhost:3001

###
GET {{url}}/users/find
Accept: application/json

###
GET {{url}}/users/find/id/
Accept: application/json
Content-Type: application/json

{
  "id": "0334b50a-dd1e-4fd2-9cfb-86018c975d7b"
}

###
GET {{url}}/users/find/email
Accept: application/json
Content-Type: application/json

{
  "email": "rafaelfarsura7@gmail.com"
}


###
POST {{url}}/users/create
Accept: application/json
Content-Type: application/json

{
  "email": "rafaelfarsura8@gmail.com",
  "password": "admin1234",
  "name": "Rafael Farsura"
}

###
POST {{url}}/auth/login
Content-Type: application/json

{
  "email": "newemail@example.com",
  "password": "newpassword123"
}

###
POST {{url}}/auth/logout
Accept: application/json
Content-Type: application/json

{
  "id": "e9d82510-6722-4014-89ea-1df2c7406393"
}

###
PATCH {{url}}/users/update?id=0334b50a-dd1e-4fd2-9cfb-86018c975d7b
Accept: application/json
Content-Type: application/json

{
  "email": "newemail@example.com",
  "password": "newpassword123",
  "name": "jonas"
}
